from . import get_bool, get_int


ENABLE_LOCAL_LLM: bool = get_bool("ENABLE_LOCAL_LLM", True)
AUTO_DOWNLOAD_LLM: bool = get_bool("AUTO_DOWNLOAD_LLM", True)
ENABLE_PROMETHEUS: bool = get_bool("ENABLE_PROMETHEUS", True)
MAX_ROWS_FIRST_PASS: int = get_int("MAX_ROWS_FIRST_PASS", 25000)
MAX_FEATURES_FIRST_PASS: int = get_int("MAX_FEATURES_FIRST_PASS", 100)
MODEL_TIME_BUDGET_SECONDS: int = get_int("MODEL_TIME_BUDGET_SECONDS", 60)
ALLOW_FULL_COMPARE_MODELS: bool = get_bool("ALLOW_FULL_COMPARE_MODELS", True)
ENABLE_HEAVY_EXPLANATIONS: bool = get_bool("ENABLE_HEAVY_EXPLANATIONS", True)

# Profiling limits
PROFILE_MAX_COLS: int = get_int("PROFILE_MAX_COLS", 200)
PROFILE_SAMPLE_ROWS: int = get_int("PROFILE_SAMPLE_ROWS", 5000)

